"""Inicijalna migracija sa novim vezama za konta i stope amortizacije

Revision ID: ed06b0307a96
Revises: 
Create Date: 2024-10-29 21:12:57.446420
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed06b0307a96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('school', schema=None) as batch_op:
        # Dodajemo use_legacy_system sa default vrednošću True
        batch_op.add_column(sa.Column('use_legacy_system', sa.Boolean(), server_default='1', nullable=False))
        batch_op.alter_column('schoolname',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('municipality',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('settings_show_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               server_default='0')

    with op.batch_alter_table('single_item', schema=None) as batch_op:
        # Dodajemo nove kolone
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('depreciation_rate_id', sa.Integer(), nullable=True))
        
        # Konvertujemo tipove podataka
        batch_op.alter_column('input_in_app_date',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('reverse_person',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('reverse_date',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)
        
        # Modifikujemo item_id da bude nullable
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Migracija podataka iz item tabele
    op.execute("""
        UPDATE single_item 
        SET category_id = (
            SELECT category_id 
            FROM item 
            WHERE item.id = single_item.item_id
        ),
        depreciation_rate_id = (
            SELECT depreciation_rate_id 
            FROM item 
            WHERE item.id = single_item.item_id
        )
        WHERE item_id IS NOT NULL
    """)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('authorization',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('authorization',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('single_item', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reverse_date',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('reverse_person',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('input_in_app_date',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('depreciation_rate_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.alter_column('settings_show_quantity',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('municipality',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('schoolname',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('use_legacy_system')

    # ### end Alembic commands ###