"""Change inventory text fields conditional type

Revision ID: 9eefff3e4898
Revises: 6c1c8489c450
Create Date: 2024-11-09 13:29:26.294315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eefff3e4898'
down_revision = '6c1c8489c450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Za SQLite, moramo koristiti batch_alter_table za izmenu tabele
    with op.batch_alter_table('building', schema=None) as batch_op:
        # SQLite ne podržava imenovane foreign key constraints
        # pa ćemo jednostavno recreirati foreign key
        batch_op.create_foreign_key(
            'fk_building_school_id', 
            'school', 
            ['school_id'], 
            ['id'], 
            ondelete='CASCADE'
        )

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_room_building_id',
            'building',
            ['building_id'],
            ['id'],
            ondelete='CASCADE'
        )

    # Izmene za Inventory tabelu
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        # SQLite ne podržava izmenu tipa kolone direktno,
        # ali u našem slučaju tip ostaje TEXT, samo menjamo implementaciju u kodu
        # tako da ne moramo praviti nikakve izmene u bazi
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_building_id', type_='foreignkey')

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_constraint('fk_building_school_id', type_='foreignkey')

    # ### end Alembic commands ###